export const G = {
  bg: "#0e0e0e",
  surface: "#161616",
  surfaceHigh: "#1f1f1f",
  border: "#2a2a2a",
  borderLight: "#333",
  accent: "#e8d5a3",
  accentDim: "#8a7a55",
  text: "#f0ede6",
  textMuted: "#888",
  textDim: "#555",
  danger: "#c0392b",
  dangerDim: "#7a1f18",
  tierColors: {
    S: "#c0392b", A: "#e67e22", B: "#f1c40f",
    C: "#27ae60", D: "#2980b9", E: "#8e44ad", F: "#555",
  },
};

export const css = {
  app: {
    fontFamily: "'Georgia', 'Times New Roman', serif",
    background: G.bg,
    color: G.text,
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    userSelect: "none",
  },
  topBar: {
    background: G.surface,
    borderBottom: `1px solid ${G.border}`,
    padding: "0 24px",
    display: "flex",
    alignItems: "stretch",
    gap: 0,
    height: 52,
  },
  tabBtn: (active) => ({
    fontFamily: "'Georgia', serif",
    fontSize: 13,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: active ? G.accent : G.textMuted,
    background: "none",
    border: "none",
    borderBottom: active ? `2px solid ${G.accent}` : "2px solid transparent",
    padding: "0 20px",
    cursor: "pointer",
    transition: "color 0.2s",
    whiteSpace: "nowrap",
  }),
  iconBtn: (danger) => ({
    background: "none",
    border: "none",
    color: danger ? G.danger : G.textDim,
    cursor: "pointer",
    padding: "4px 6px",
    fontSize: 14,
    lineHeight: 1,
    borderRadius: 3,
    transition: "color 0.15s",
  }),
  primaryBtn: {
    fontFamily: "'Georgia', serif",
    fontSize: 12,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    background: G.accent,
    color: G.bg,
    border: "none",
    padding: "7px 16px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  ghostBtn: {
    fontFamily: "'Georgia', serif",
    fontSize: 12,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    background: "none",
    color: G.textMuted,
    border: `1px solid ${G.border}`,
    padding: "6px 14px",
    cursor: "pointer",
  },
  input: {
    fontFamily: "'Georgia', serif",
    fontSize: 13,
    background: G.surfaceHigh,
    color: G.text,
    border: `1px solid ${G.border}`,
    padding: "7px 10px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  label: {
    fontSize: 11,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: G.textMuted,
    display: "block",
    marginBottom: 5,
  },
  modal: {
    position: "fixed", inset: 0, zIndex: 1000,
    background: "rgba(0,0,0,0.75)",
    display: "flex", alignItems: "center", justifyContent: "center",
  },
  modalBox: {
    background: G.surface,
    border: `1px solid ${G.border}`,
    padding: 28,
    minWidth: 340,
    maxWidth: 560,
    width: "90vw",
    maxHeight: "90vh",
    overflowY: "auto",
  },
};
